name: splat-render
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - pyopengl
      - glfw
      - tqdm
      - numpy
      - matplotlib
      - pyglm
      - vulkan
